brainandforce/Electrum.jl

- src/Xtal.jl
- src/filetypes.jl
This is my first time attempting to merge a pull request...
> Added XYZ reading functionality

- src/abinit.jl
- src/atoms.jl
- src/data.jl
- src/lattices.jl
- src/show.jl
- src/vasp.jl
Some of the parsers were broken when I converted basis vectors to their own type - this should fix it.
> Parser fixes

- CONTRIBUTING.md
- README.md
- src/vasp.jl
Just updated the documentation to reflect the package's new capabilities. Also included is a fix for a missing space in the `readWAVECAR()` debug messages.
> Documentation update

- src/Xtal.jl
- src/data.jl
- src/vasp.jl
Added functionality to read PROCAR files and store them in a FatBands struct.
> Added readPROCAR()

- src/Xtal.jl
- src/data.jl
- src/filetypes.jl
- src/lattices.jl
- src/potentials.jl
- src/show.jl
- src/types.jl
- src/vasp.jl
Perhaps this would have been better off as two different sets of pull requests, but I did both at once so...
> Datagrid math and pseudopotential tools

- Project.toml
- README.md
- src/Xtal.jl
- src/abinit.jl
- src/data.jl
- src/filetypes.jl
- src/show.jl
Welp, didn't expect to bump to a new version that fast...
> Added CP reading + fixed serious problem with ABINIT datagrid reading

- Project.toml
- src/crystals.jl
- src/data.jl
- src/lattices.jl
Here are some fixes for some problems with method definitions with `BasisVectors` and `SphericalComponents`.
> Method fixes

- src/data.jl
Fixing bug for functionality to read and plot DOS
> Additional corrections to projected DOS

- src/data.jl
- src/software/vasp.jl
readPROCAR can now read phase-decomposed PROCARs
> Reads lm- and phase-decomposed PROCARs

- src/Xtal.jl
- src/crystals.jl
- src/data.jl
- src/lattices.jl
- src/show.jl
The definitions for `RealSpaceDataGrid` addition and multiplication are shortened, and now there is an `integrate()` method.
> New and improved datagrid operations

- Project.toml
- src/Xtal.jl
- src/crystals.jl
- src/data.jl
- src/lattices.jl
- src/show.jl
- src/software/abinit.jl
The `integrate()`, `voxelsize()`, and other `RealSpaceDataGrid` methods are all going to come in handy for some things I'm working on, so I figured it's time to merge.
> Merge for version 0.1.9

- Project.toml
- src/Xtal.jl
- src/data.jl
Added Gaussian smearing for DOS
> Gaussian smearing for DOS 

- src/data.jl
Accidentally overwrote the commits I intended to merge here - doing this again
> Datagrid subtraction and indexing update (redo after force push issue)

- src/Xtal.jl
- src/data.jl
- src/lattices.jl
- src/software/abinit.jl
- src/software/vasp.jl
I had to change up a good number of details in `ReciprocalWavefunction` to get this to work (and I may end up reverting some of them) but hopefully this will be useful to everyone.
> Ability to read abinit wavefunction (WFK) files

- src/data.jl
Fixed smear using fft and permuting gaussian
> Dos smearing 

- src/data.jl
- src/lattices.jl
This breaks compilation so I'm merging immediately.
> Moved `dspacing(::RealSpaceDataGrid)` to a place where `RealSpaceDataGrid is defined`

- src/data.jl
@lcgarman needed this for performing some of the diffraction pattern analysis, so I figured it would be best to just add it to the package.
> Defined `abs()` and `abs2()` for `HKLData` (again)

- src/Xtal.jl
- src/atoms.jl
- src/software/vasp.jl
This made a slight change in the constructors for `AtomPosition` so I hope this doesn't break anything. Should be fine for the most part.
> Added ability to read POSCAR files

- README.md
- src/Xtal.jl
- src/atoms.jl
- src/crystals.jl
- src/filetypes.jl
This has been a long time coming but it was not difficult to implement at all!
> Ability to write XYZ files

- Project.toml
- README.md
- src/Xtal.jl
- src/atoms.jl
- src/crystals.jl
- src/data.jl
- src/filetypes.jl
This adds a fix for FFT normalization and some new functions to link voxels in a `RealSpaceDataGrid` to positions.
> Merge for version 0.1.13: the Unlucky Update

- src/data.jl
Now `keys()`, `LinearIndices()`, `CartesianIndices()`, and `eachindex()` have been defined for `RealSpaceDataGrid`.
> Datagrid iterator updates

- Project.toml
- src/data.jl
- src/show.jl
That was a quick one, but I managed to get a good number of new features included.
> Merge for version 0.1.14

- src/data.jl
This should significantly reduce the amount of typing we'll need...
> Added definitions for `/`, `abs()`, `abs2()`, `angle()`, and `conj()`

- Project.toml
- src/Xtal.jl
- src/data.jl
- src/filetypes.jl
- src/show.jl
- src/vectors.jl
Adds in some updates to `HKLData`, tools for binning FFT frequencies, and updates to show methods.
> Release version 0.1.15

- Project.toml
- src/data.jl
I need the integration improvements for some other work I'm doing...
> Merge for version 0.1.16

- Project.toml
- src/Xtal.jl
- src/data.jl
- src/lattices.jl
The fix to the `BasisVectors` iteration protocol warrants a version bump.
> Bump version number to 0.1.17

- Project.toml
I screwed up the pull request for LAMMPS data writing so I'm just gonna bump the version number...
> Bumped version number to 0.1.18

- Project.toml
- src/Xtal.jl
- src/data.jl
- src/vectors.jl
I fixed some a serious but with `fftfreq(::RealSpaceDataGrid)` and some of the exports.
> Version bump to 0.1.19

- src/lattices.jl
Just made some change to reorganize a large part of `lattices.jl` and make some fixes to docstring and comments that were out of date.
> Fix angles

- Project.toml
- src/Xtal.jl
- src/atoms.jl
- src/crystals.jl
- src/lattices.jl
- src/software/vasp.jl
Adds POSCAR writing functionality, improves POSCAR reading, unifies the `AbstractCrystal` APIs and properties, and rearranges some of `lattices.jl` for clarity.
> Update to version 0.1.20

- src/software/vasp.jl
Now allows for the specification of a comment line and the option to turn on atomic identity specification.
> POSCAR options

- Project.toml
- src/data.jl
I'm pushing a release now so that I can use the ability to rescale spherical harmonics.
> Merge for 0.1.22

- .github/workflows/TagBot.yml
- .github/workflows/documentation.yml
This should automatically generate documentation for Xtal.jl from the source files.
> Doc deployment

- README.md
Now that documentation is working, I've added badges to the README to make this repo look like a proper package. There's also a few updates reflecting new capabilities that have been added.
> README updates with badges and new capabilities

- test/Project.toml
- test/runtests.jl
It's already caught a number of problems in the package, so this is definitely a good addition overall!
> Added Aqua.jl for more extensive testing

- .github/workflows/CI.yml
- Project.toml
This should ensure that the package tests are run automatically whenever a pull request is made or something is merged.
> Added more continuous integrations for testing

- src/show.jl
The code for this was really messy, but I've fixed it up and added a show method for `HKLData`. I've also added in basis vector printing for `ReciprocalSpaceWavefunction.`
My main question to @pcross0405 and @xamberl before merging: what other information would be useful to display with the data types you use on a regular basis?
> Refactor show methods

- Project.toml
- src/Xtal.jl
- src/atoms.jl
- test/runtests.jl
- test/supercell.jl
I think I figured it out - I need get the translation bounds from the Smith normal form of the matrix. In order to do this, I wrote [NormalForms.jl](https://github.com/brainandforce/NormalForms.jl) - which might be overkill, but at least it gets the job done.
> Final supercell construction fix??

- src/data/reciprocalspace.jl
I'm not entirely sure of the numerical stability/correctness of the procedure, but I tried my best.
> Added Fermi energy calculation for wavefunctions

- src/Xtal.jl
- src/software/abinit.jl
This time it should work - pulled from main branch to add new the new function to read the phonon density of states. We can delete whatever happened with the last branch.
> New function to read phonon DOS

- src/data/wavefunctions.jl
- src/lattices.jl
This should resolve #160 - @xamberl feel free to give this one a test.
> Fix show method for `PlanewaveWavefunction`/make it nicer for `AbstractBasis`

- CHANGELOG.md
- src/data/grids.jl
- test/datagrids.jl
This is intended to close #170.
> Fixed voxel size calculation

- CHANGELOG.md
- docs/src/api/data.md
- src/Electrum.jl
- src/data/grids.jl
- src/math.jl
- test/datagrids.jl
- test/internals.jl
This should make it significantly easier to calculate these quantities when needed in other packages.
> Partial derivatives, gradients, directional derivatives

- CHANGELOG.md
- src/software/xcrysden.jl
The unit reading/writing was not correctly implemented for XSF files, but this has been corrected.
> Fix more XSF reading/writing bugs
