- src/atoms.jl
- src/data.jl
Before this fix: the package would build, but would warn about fatally broken incremental compilation due to an unintended override of the inner constructor of `ProjectedDensityofStates`.
Not sure where the change to `Base.getindex(::AtomList)` happened, but I'll just leave that in for now...I'll try to be better about that in the future...
> Incremental compile fix

- Project.toml
- src/filetypes.jl
- src/lattices.jl
We still need to figure out how to best handle the matrix type stability problem and the use of `BasisVectors` because this is a little annoying.
> Fixed improper use of `BasisVectors` that broke `readXSF3D()`

- src/data.jl
There wasn't a varargs constructor for `SphericalComponents` but that was intended to be added in v0.1.4.
> Added missing `SphericalComponents` constructor

- Project.toml
- src/data.jl
- src/lattices.jl
The string escaping I used in some of the long error strings associated with `@assert` were breaking compilation on Julia 1.6.
The fix has been tested in Julia 1.6.6. In the future, we'll have to enforce a standard, 1.6-compatible method of string splitting.
> Fixed string escaping that wasn't compatible with Julia 1.6

- src/atoms.jl
- src/crystals.jl
- src/filetypes.jl
- src/software/abinit.jl
It appears that this function was not updated after the changeover to `BasisVectors` (as opposed to `SMatrix`), and some of the methods that were being used to get components of `CrystalWithDatasets` were not actually present!
> Fix to get `writeXSF()` working again

- src/Xtal.jl
- src/lattices.jl
- src/software/abinit.jl
I realized that `lengths()` and `volume()` were not defined for `BasisVectors` but they really need to be.
Also, `read_abinit_potential` and `read_abinit_density` needed docstrings.
> Consistent function names

- src/data.jl
Now you can subtract and negate a `RealSpaceDataGrid`, and you can index them arbitrarily by any positive or negative index (which loops around, so that for `g::RealSpaceDataGrid{3,Float64}`,`g[0, 0, 0] === g[gridsize(g)]`)
> Datagrid subtraction and indexing update

- src/data.jl
Since Julia has the `Complex{Float64}` type I figured it might be a good idea to combine these two fields. However, @xamberl I'm giving you final say on whether this gets merged since it'll probably affect the notebooks you've written.
Feel free to pull this branch locally and make your own commits to it as well.
> Combine real and imaginary components of `FatBands` into a single field

- CONTRIBUTING.md
- README.md
- src/Xtal.jl
- src/data.jl
- src/lattices.jl
- src/software/abinit.jl
- src/vectors.jl
Both the README and CONTRIBUTING documents have changed, as well as the format of many docstrings. In particular, unexported objects should always be prefixed with `Xtal.` in their docstrings. If you spot any cases where this was not done (or done incorrectly), feel free to push changes to this branch.
> Big documentation update

- src/lattices.jl
I'd appreciate it if someone can check that the formula I'm using is correct! (Of note: `dual()` returns a new `BasisVectors` that has units of inverse length, but *not* multiplied by 2π)
> Calculation of d-spacing (distance between crystallographic planes)

- src/data.jl
I figured we'd need ways of getting the backing array out of an HKLData.
> `grid()` for `HKLData`

- src/software/vasp.jl
This should in principle fix #57 but I'll have @xamberl review this change (I don't have any PROCAR files to test on yet)
> Fixed `readPROCAR()` to use updated `FatBands` constructor

- src/filetypes.jl
- src/lattices.jl
I've found that there were a lot of broken constructors and unnecessary type parameters included for `RealLattice` and `ReciprocalLattice`. This should clear a lot of that up, and I've updated `readXSF3D()` and various methods for reading abinit outputs to handle the change in constructors.
> Numerous fixes for lattice constructors

- src/Xtal.jl
- src/data.jl
- src/types.jl
I made this happen earlier (#54) but found that it would actually make the wavefunction file storage problem much worse. I'm suggesting that this feature be merged but without any changes to `ReciprocalWavefunction`.
> Created `HKLDict` struct (dictionary storage for reciprocal space data)

- src/atoms.jl
- src/crystals.jl
- src/filetypes.jl
- src/software/abinit.jl
- src/software/vasp.jl
These types have inner constructors that require the supply of the dimension type parameter, but at the same time the constructors require the use of types that already have dimension information (for instance, `SVector{D,T}`, `BasisVectors{D}`). I believe I've fixed all calls to these functions within the library, but let me know if this breaks other functionality you may be using.
> Removal of more unnecessary type parameters (for `AtomPosition`, `AtomList`, and `Crystal`)

- Project.toml
- src/crystals.jl
It was inheriting from `AbstractCrystalData` and not `AbstractCrystal`
> Fixed broken subtyping for `CrystalWithDatasets`

- src/data.jl
I've extended the `integrate()` function to allow for the application of an arbitrary function to a `RealSpaceDataGrid` elementwise. This should be useful when integrating wavefunctions to get the electron density: you can call `integrate((x -> x^2), g)` to square the values of the grid `g` before integrating it.
In a similar vein, I've added a new `RealSpaceDataGrid` constructor that can generate a new `RealSpaceDataGrid` with some function applied.
> Applying functions to `RealSpaceDataGrid`

- src/data.jl
I forgot that FFTs scale with the number of grid points, so I needed to compensate for that. (Also, the size of the cell too - that's pretty important)
> Fixed scaling for FFT result

- src/show.jl
`BasisVectors`, `Crystal`, `RealLattice`, `ReciprocalLattice` and `RealSpaceDataGrid` will now show default units (angstroms or cubic angstroms). Some of the internal functions uses to generate strings will also support the `unit` keyword for unit specification.
This should serve as a visual reminder when working with lengths, because some packages may use Bohr or other units for that purpose.
> Added unit support to display methods for objects with units

- src/data.jl
Apparently not having `length()` defined for `RealSpaceDataGrid` breaks multiplication and iteration...
> Datagrid length

- src/data.jl
- src/show.jl
This is necessary for correctly performing FFTs, since `RealSpaceDataGrid` has the basis vectors provided.
Note that the newly defined `basis(::HKLData)` returns the *real space* vectors in accordance with all other instances of `basis()`. In the future I do want to have `RealBasis` and `ReciprocalBasis` be their own types.
As one final test, the varinfo output for the WAVECAR I use for testing is given below:
```julia-repl
julia> varinfo(r"ans")
name        size summary                           
–––– ––––––––––– ––––––––––––––––––––––––––––––––––
ans  547.819 MiB ReciprocalWavefunction{3, Float32}
```
This is a ~350 KiB increase from before (547.466 MiB), so overall the additional data is not very significant.
> Added basis vector specification to `HKLData`

- src/data.jl
I found this to be a problem when integrating vector fields. In principle, `T` can be anything as long as `f()` returns a number type.
> Broadened `integrate(f::Function, g::RealSpaceDataGrid{D,T})` to accept any data type `T`

- src/data.jl
It's pretty useful to get frequency bins when performing an FFT on a `RealSpaceDataGrid` (for instance, for taking derivatives/gradients/Laplacians). This overload should help with that.
> `FFT.fftfreq()` for `RealSpaceDataGrid`

- src/lattices.jl
The iteration protocol for `BasisVectors` was broken, so I fixed that. I also fixed `lengths()` so that it returns an `SVector{D,Float64}` for `BasisVectors` arguments (previously returned a `Vector{Float64}`).
> Fixes and improvements for `BasisVectors`

- src/data.jl
The arguments to `fftfreq()` are supposed to be the number of samples and the sampling rate, but the length of the basis vector was use instead of the sampling rate along that vector.
> Fftfreq fix

- src/Xtal.jl
- src/vectors.jl
It seems that `supercell()` wasn't exported in 0.1.18, and `triangularize()` probably also deserved to be exported as well.
> API updates with export fixes

- src/Xtal.jl
- src/atoms.jl
- src/crystals.jl
- src/software/vasp.jl
The new functionality should allow writing of VASP 4.6 format POSCAR files. There's also some additions such as `atomtypes()` and sorting an `AtomList` by atomic number.
> POSCAR writing functionality (VASP 4.6)

- src/atoms.jl
It appears that calling it with an argument that wasn't an `SMatrix` or `SVector` would cause it to throw an error. This should be fixed now.
I also don't know if we needed to account for the permutations involved in the LU decomposition that's used to generate the supercell, but I've included code to do so.
> Fix `supercell()`

- Project.toml
- src/atoms.jl
- src/software/vasp.jl
The bug with `supercell()` has been fixed and there are more options for writing POSCAR files.
> Merge for version 0.1.21

- src/data.jl
Scalar multiplication is now defined for spherical harmonics, so rescaling data should be much easier.
> Scale spherical harmonics

- src/Xtal.jl
- src/lattices.jl
- src/show.jl
- src/types.jl
Eventually these should replace `BasisVectors` as the favored representation of a set of crystal basis vectors, as they have a notion of units (`RealBasis` being in length and `ReciprocalBasis` being in inverse length). All of the functionality that `BasisVectors` has should be extended to `AbstractBasis`.
In the future I will refactor `AbstractLattice` and its subtypes to use these new types internally.
> New `AbstractBasis`, `RealBasis` and `ReciprocalBasis` types

- src/data/reciprocalspace.jl
- src/software/abinit.jl
- src/software/vasp.jl
I've also added a definition of `basis()` for `ReciprocalWavefunction` for good measure.
Both `readWAVECAR()` and `read_abinit_wavefunction()` have been updated to include energy and occupancy data from the file in the returned `ReciprocalWavefunction`.
> Adding energy and occupancy data to `ReciprocalWavefunction`

- Project.toml
- src/Xtal.jl
It seems that `sort_atomicno()` was misspelled in the export directive, so this has now been fixed.
> Fix broken sort export

- src/show.jl
I've cleaned up a good amount of the code and added some extra functionality: now formula string printing is supported for `AtomList` and `AbstractCrystal`. Most of these changes involve internal APIs so users shouldn't really be affected besides that.
> Refactoring of show methods

- src/software/vasp.jl
Fixes `incrementHKL!` in the `readWAVECAR` function where it goes out of bounds (+1).
> Fix `incrementHKL` to stay within bounds

- src/data/reciprocalspace.jl
- src/software/abinit.jl
- src/software/vasp.jl
This should allow for a lone `HKLData` struct to be more easily dealt with, as the associated k-point will be included. No need to go back and reference a `KPointGrid` or `KPointList` repeatedly.
I've also updated the logic of `read_abinit_wavefunction()` and `readWAVECAR()` to include the k-points explicitly. I haven't checked how FFTs are handled, but the default constructor for `HKLData` will insert a zero k-point vector if it's not explicitly specified.
> Adding k-points to `HKLData`

- src/data/reciprocalspace.jl
- src/show.jl
- test/kpoints.jl
- test/runtests.jl
Now if a range of k-points is used as the index, the object returned is another `KPointList`. This is a temporary fix as #150 should completely rework a lot of the `KPointList` internals.
But I've also included pretty printing methods for `KPointList` which should be relevant even afterwards.
> Fixed indexing for `KPointList`

- codecov.yml
That includes `src/metrics.jl`, which isn't used, and `src/show.jl` which doesn't really need testing.
> Excluded irrelevant files from codecov

- src/Electrum.jl
- src/data/fft.jl
- src/data/grids.jl
- src/math.jl
- test/datagrids.jl
I've created the new `FFTBins` and `FFTLength` types that can be used to work with data that's been Fourier transformed and types whose indices are effectively FFT bins.
> Tools for working with FFT binning

- docs/src/api/filetypes.md
- docs/src/filetypes.md
- src/Electrum.jl
- src/precompile.jl
- src/software/abinit.jl
- test/runtests.jl
Until now there were pairs of functions that did the same thing: `read_abinit_density()` and `read_abinit_DEN()`, `read_abinit_potential()` and `read_abinit_POT()`, and `read_abinit_wavefunction()` and `read_abinit_WFK()`.
My future design plan is to have functions like `read_abinit_density()` return only the associated datagrid, and `read_abinit_DEN()` return the datagrid as part of a `CrystalWithDatasets` (or perhaps a similar future type that replaces it). So the aliasing of function names is being dropped.
@xamberl I'm going to loop you in on this
> Updating names of abinit file reading functions

- docs/src/types.md
- src/Electrum.jl
- src/atoms.jl
- src/data/realspace.jl
- src/lattices.jl
- src/show.jl
- src/software/abinit.jl
- src/software/lammps.jl
- src/software/vasp.jl
- src/types.jl
- test/filetypes.jl
I've converted `RealBasis` and `ReciprocalBasis` to using bohr as the default length unit (and rad\*bohr⁻¹ for inverse length). By default, energy units are assumed to be in Hartree. (Packages like VASP that don't use Hartree atomic units by default have their inputs converted to match the package's conventions)
> Use Hartree atomic units everywhere

- src/show.jl
- src/software/abinit.jl
- test/filetypes.jl
- test/runtests.jl
Although `Electrum.read_abinit_header()` is not exported, it is now easier to use, as it accepts a generic file name/path argument as well as an I/O handle. I've also defined equality for `Electrum.ABINITHeader` objects, and fixed `setindex!()` for them.
> More testing/functionality for abinit headers

- src/software/abinit.jl
I noticed that some of the methods for abinit file writing didn't conform to the (informal, undocumented) standard for file processing methods. Along with having the methods comply with that standard, I refactored them slightly and included some comments for improvement. I realize I should have been more proactive with that feedback earlier on. Since I don't work with anaddb I'd like to get your feedback before merging.
As a future note, I'm going to include some extra documentation for how to contribute file writing methods. The tl;dr is that every file writing function should have a method that accepts a file handle (Julia `IO` subtypes, see the method signatures that contain `(io::IO, args...; kwargs...)`) and then another method that accepts a path. By default we assumed that this was …
> Helping abinit file reading/writing functions conform with standards

- CHANGELOG.md
- src/lattices.jl
- test/lattices.jl
This is intended to fix #169. In general, I may have to keep an eye on how I implemented older iteration through basis vectors, as the iteration specification has changed.
> Fixed definition of the `lengths()` function for basis vectors

- CHANGELOG.md
- src/software/abinit.jl
I performed some norm-conserving pseudopotential calculations with abinit 9.10.1 and fixed a bug which now enables support for that version. Previously, Electrum only officially had support for abinit 7.10.5 and 8.10.3.
> Support for abinit 9.10.1 outputs

- CHANGELOG.md
- Project.toml
- README.md
- docs/src/api/filetypes.md
- docs/src/filetypes.md
- src/Electrum.jl
- src/software/toml.jl
- test/Project.toml
- test/filetypes.jl
This should allow direct export of data to TOML files. When the TOML module is loaded, the `writeTOML()` function is exported, and `Electrum.toml_convert()` allows for Electrum data types to be converted to a type usable by `TOML.print()`.
> TOML writing support

- CHANGELOG.md
- src/data/grids.jl
- test/datagrids.jl
Because the Cartesian indices are periodic, inbound array access is already guaranteed. This should speed things up a bit.
This change has not altered the behavior of linear indexing, which does involve bounds checking by default (and can be overridden with `@inbounds` if desired).
> Eliminate bounds checking for `DataGrid`

- CHANGELOG.md
- docs/src/api/lattices.md
- src/Electrum.jl
- src/lattices.jl
- src/traits.jl
Back when the type system wasn't as well developed, I had an `AbstractBasis{D}` type that encompassed both `RealBasis{D}` and `ReciprocalBasis{D}`. Now that `Electrum.LatticeBasis{S,D,T}` is the foundation for the types, I've added back this `AbstractBasis` type as an alias for convenience.
To faciliate this, I've grouped `Electurm.ByRealSpace{D}` and `Electrum.ByReciprocalSpace{D}` into a supertype, `Electrum.BySpace{D}`.
> Added back `AbstractBasis` type

- src/data/kpoints.jl
- test/kpoints.jl
This can cause serious problems when reading wavefunction files where the k-point coordinate is slightly above 0.5 or below -0.5.
> Remove automatic k-point rounding

- CHANGELOG.md
- Project.toml
- src/Electrum.jl
- src/atoms.jl
- test/atoms.jl
- test/runtests.jl
The InlineStrings.jl package provides string types that are pure bits, which should avoid all of the weirdness with `NTuple{8,Char}` used for the `NamedAtom` type internally.
The only problem that arises with adding InlineStrings.jl is the method ambiguities for `Base.Sort.defalg` and `Base.unsafe_convert`, which Aqua throws an error for, so testing of these functions for ambiguities is manually excluded. The latter may be fixed in a pull request for InlineStrings.jl, but the `Base.Sort.defalg` ambiguity might actually be an issue with Julia Base.
> `NamedAtom` now uses the `InlineString15` type for its field

- CHANGELOG.md
- docs/src/api/data.md
- src/Electrum.jl
- src/data/wavefunctions.jl
- test/wavefunctions.jl
Along with `fermi(::PlanewaveWavefunction)` this should help package users get this critical data without having to dive into the internals of `PlanewaveWavefunction` objects.
> Add `min_energy(::PlanewaveWavefunction)` and `max_energy(::PlanewaveWavefunction)`

- CHANGELOG.md
- src/lattices.jl
- src/traits.jl
- test/internals.jl
The `Electrum.dimension` function returns the dimension parameter associated with a `DataSpace` object. For now, this assumes that the type parameter is an integer, but in the future we may want to handle things like metric tensors which provide some notion of a number of dimensions, but are not integers themselves.
`Electrum.DataSpace` now has a new fallback when a type is given instead of an object:
```julia
DataSpace(::Type{T}) where T = DataSpace(fieldtype(T, :basis))
```
Therefore, by default, a new type with a `basis` field will automatically infer from the field's type. This can be overridden if needed for specific types.
> New `Electrum.dimension` internal function and upgrades to `Electrum.DataSpace` methods

- CHANGELOG.md
- src/data/wavefunctions.jl
- src/software/abinit.jl
- test/filetypes.jl
Previously we noticed that `read_abinit_WFK` did not store the `KPointMesh` from the header data. This should fix #191.
> `read_abinit_WFK` stores k-point mesh correctly

- CHANGELOG.md
- docs/src/api/data.md
- src/Electrum.jl
- src/data/wavefunctions.jl
- test/wavefunctions.jl
In many cases, a wavefunction will have a significant number of G-vectors with no coefficients ever having a nonzero value. This allows a user to obtain a `Vector{CartesianIndex{D}}` or a `Vector{SVector{D}}` of the nonzero G-vectors depending on the need.
> `nonzero_g_indices` and `nonzero_g_vectors` functions

- CHANGELOG.md
- src/data/energies.jl
- src/lattices.jl
- test/runtests.jl
- test/wavefunctions.jl
It appears I had the wrong definitions for `energies` and `occupancies` on generic objects, so that's been fixed.
`Electrum.LatticeBasis{S}` now has `S` subtype `Electrum.BySpace` instead of `Union{Electrum.ByRealSpace,Electrum.ByReciprocalSpace}`.
> Fixes for `LatticeBasis` and `energies`/`occupancies`

- CHANGELOG.md
- docs/src/api/data.md
- src/Electrum.jl
- src/data/spin.jl
- src/show.jl
- test/runtests.jl
- test/spin.jl
This type should facilitate indexing of some new data types by spin state. `SpinRange{M}` has a single type parameter, the multiplicity `M`, which is an `Int`, and it behaves like `UnitRange(-(M-1)//2, (M-1)//2)`, where all elements are valid angular momenta for that multiplicity.
I am willing to go back and rename this type to `Multiplicity` or something else, because even though `SpinRange` is an `AbstractUnitRange`, the type parameter `M` is the spin multiplicity.
> New `Multiplicity{M}` type

- CHANGELOG.md
- docs/src/api/lattices.md
- src/Electrum.jl
- src/lattices.jl
- test/lattices.jl
This iterator should let a user run through each vertex of the parallelepiped spanned by the basis vectors of a lattice given by an `AbstractMatrix`.
> `eachvertex` iterator for `RealBasis`, `ReciprocalBasis`, and even `AbstractMatrix` types

- CHANGELOG.md
- docs/src/api/lattices.md
- src/Electrum.jl
- src/data/grids.jl
- src/lattices.jl
- src/traits.jl
- test/internals.jl
- test/lattices.jl
The new `dual` and `dualbasis` functions should return the dual lattice as needed.
> `inv(::LatticeBasis)` should return the matrix inverse, not the dual lattice

- CHANGELOG.md
- docs/make.jl
- docs/src/api/traits.md
- docs/src/lattices.md
- src/Electrum.jl
- src/data/grids.jl
- src/data/spin.jl
- src/data/wavefunctions.jl
- src/lattices.jl
- src/software/toml.jl
- src/traits.jl
- src/vectors.jl
- test/internals.jl
- test/kpoints.jl
- test/spin.jl
Notably, the `DataSpace` trait function has been internally deprecated and replaced with `BySpace`. There are also some new functions for checking that traits of different objects are compatible.
> `BySpace` and `ByCoordinate` traits have been refactored and exported
